extend type Access {
  """
  ✨ Implicit foreign key field based on `Access`.`beach`. It must match the value of `Beach`.`id`. See `@ref` for how to customize it.
  """
  beachId: UUID! @fdc_generated(from: "Access.beach", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Access`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String @fdc_generated(from: "Access.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Beach {
  """
  ✨ Implicit foreign key field based on `Beach`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String @fdc_generated(from: "Beach.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Comment {
  """
  ✨ Implicit foreign key field based on `Comment`.`beach`. It must match the value of `Beach`.`id`. See `@ref` for how to customize it.
  """
  beachId: UUID! @fdc_generated(from: "Comment.beach", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Comment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Comment.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Report {
  """
  ✨ Implicit foreign key field based on `Report`.`access`. It must match the value of `Access`.`id`. See `@ref` for how to customize it.
  """
  accessId: UUID! @fdc_generated(from: "Report.access", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Report`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String @fdc_generated(from: "Report.user", purpose: IMPLICIT_REF_FIELD)
}
