extend type Access {
  """
  ✨ List `Report` objects in a one-to-many relationship (where `Report`.`access` is this object).
  """
  reports_on_access(
    """
    Filter condition to narrow down the query results.
    """
    where: Report_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Report_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Report_Having
  ): [Report!]! @fdc_generated(from: "Report.access", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Access", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Access` table.
  """
  _count: Int! @fdc_generated(from: "Access.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `alcoholAllowed` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  alcoholAllowed_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.alcoholAllowed", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `beachId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  beachId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.beachId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `blockerDescription` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  blockerDescription_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.blockerDescription", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `blockerName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  blockerName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.blockerName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `blockerType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  blockerType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.blockerType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `campingAllowed` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  campingAllowed_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.campingAllowed", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `cellular4G` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cellular4G_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.cellular4G", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `feeRequired` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  feeRequired_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.feeRequired", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `illegalFeeAmount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  illegalFeeAmount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.illegalFeeAmount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `images` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  images_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.images", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `isPendingCuration` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPendingCuration_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.isPendingCuration", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `latitude` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  latitude_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.latitude", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `longitude` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  longitude_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.longitude", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `parkingReserved` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  parkingReserved_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.parkingReserved", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `parking` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  parking_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.parking", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `pets` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pets_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.pets", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `ramps` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ramps_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.ramps", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `reputation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reputation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.reputation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `security` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  security_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.security", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `shade` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  shade_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.shade", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `showers` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  showers_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.showers", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `trailGeometry` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trailGeometry_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.trailGeometry", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `wheelchair` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  wheelchair_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.wheelchair", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Access` table where the `wifi` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  wifi_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Access.wifi", purpose: QUERY_COUNT)
  """
  ✨ Sum the `illegalFeeAmount` field in the `Access` table.
  """
  illegalFeeAmount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.illegalFeeAmount", purpose: QUERY_SUM)
  """
  ✨ Sum the `latitude` field in the `Access` table.
  """
  latitude_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.latitude", purpose: QUERY_SUM)
  """
  ✨ Sum the `longitude` field in the `Access` table.
  """
  longitude_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.longitude", purpose: QUERY_SUM)
  """
  ✨ Sum the `reputation` field in the `Access` table.
  """
  reputation_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Access.reputation", purpose: QUERY_SUM)
  """
  ✨ Average the `illegalFeeAmount` field in the `Access` table.
  """
  illegalFeeAmount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.illegalFeeAmount", purpose: QUERY_AVG)
  """
  ✨ Average the `latitude` field in the `Access` table.
  """
  latitude_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.latitude", purpose: QUERY_AVG)
  """
  ✨ Average the `longitude` field in the `Access` table.
  """
  longitude_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.longitude", purpose: QUERY_AVG)
  """
  ✨ Average the `reputation` field in the `Access` table.
  """
  reputation_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Access.reputation", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Access` table.
  """
  createdAt_min: Date @fdc_generated(from: "Access.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `illegalFeeAmount` field in the `Access` table.
  """
  illegalFeeAmount_min: Float @fdc_generated(from: "Access.illegalFeeAmount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `images` field in the `Access` table.
  """
  images_min: Any @fdc_generated(from: "Access.images", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `latitude` field in the `Access` table.
  """
  latitude_min: Float @fdc_generated(from: "Access.latitude", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `longitude` field in the `Access` table.
  """
  longitude_min: Float @fdc_generated(from: "Access.longitude", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `reputation` field in the `Access` table.
  """
  reputation_min: Int @fdc_generated(from: "Access.reputation", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `trailGeometry` field in the `Access` table.
  """
  trailGeometry_min: Any @fdc_generated(from: "Access.trailGeometry", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Access` table.
  """
  createdAt_max: Date @fdc_generated(from: "Access.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `illegalFeeAmount` field in the `Access` table.
  """
  illegalFeeAmount_max: Float @fdc_generated(from: "Access.illegalFeeAmount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `images` field in the `Access` table.
  """
  images_max: Any @fdc_generated(from: "Access.images", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `latitude` field in the `Access` table.
  """
  latitude_max: Float @fdc_generated(from: "Access.latitude", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `longitude` field in the `Access` table.
  """
  longitude_max: Float @fdc_generated(from: "Access.longitude", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `reputation` field in the `Access` table.
  """
  reputation_max: Int @fdc_generated(from: "Access.reputation", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `trailGeometry` field in the `Access` table.
  """
  trailGeometry_max: Any @fdc_generated(from: "Access.trailGeometry", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Access.id", purpose: GLOBAL_ID)
}
extend type Beach {
  """
  ✨ List `Access` objects in a one-to-many relationship (where `Access`.`beach` is this object).
  """
  accesses_on_beach(
    """
    Filter condition to narrow down the query results.
    """
    where: Access_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Access_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Access_Having
  ): [Access!]! @fdc_generated(from: "Access.beach", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Comment` objects in a one-to-many relationship (where `Comment`.`beach` is this object).
  """
  comments_on_beach(
    """
    Filter condition to narrow down the query results.
    """
    where: Comment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Comment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Comment_Having
  ): [Comment!]! @fdc_generated(from: "Comment.beach", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Beach", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Beach` table.
  """
  _count: Int! @fdc_generated(from: "Beach.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `boundaryPolygon` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  boundaryPolygon_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.boundaryPolygon", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `images` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  images_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.images", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `latitude` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  latitude_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.latitude", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `longitude` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  longitude_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.longitude", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `state` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  state_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.state", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beach` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beach.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `latitude` field in the `Beach` table.
  """
  latitude_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Beach.latitude", purpose: QUERY_SUM)
  """
  ✨ Sum the `longitude` field in the `Beach` table.
  """
  longitude_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Beach.longitude", purpose: QUERY_SUM)
  """
  ✨ Average the `latitude` field in the `Beach` table.
  """
  latitude_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Beach.latitude", purpose: QUERY_AVG)
  """
  ✨ Average the `longitude` field in the `Beach` table.
  """
  longitude_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Beach.longitude", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `boundaryPolygon` field in the `Beach` table.
  """
  boundaryPolygon_min: Any @fdc_generated(from: "Beach.boundaryPolygon", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Beach` table.
  """
  createdAt_min: Date @fdc_generated(from: "Beach.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `images` field in the `Beach` table.
  """
  images_min: Any @fdc_generated(from: "Beach.images", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `latitude` field in the `Beach` table.
  """
  latitude_min: Float @fdc_generated(from: "Beach.latitude", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `longitude` field in the `Beach` table.
  """
  longitude_min: Float @fdc_generated(from: "Beach.longitude", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `boundaryPolygon` field in the `Beach` table.
  """
  boundaryPolygon_max: Any @fdc_generated(from: "Beach.boundaryPolygon", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Beach` table.
  """
  createdAt_max: Date @fdc_generated(from: "Beach.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `images` field in the `Beach` table.
  """
  images_max: Any @fdc_generated(from: "Beach.images", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `latitude` field in the `Beach` table.
  """
  latitude_max: Float @fdc_generated(from: "Beach.latitude", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `longitude` field in the `Beach` table.
  """
  longitude_max: Float @fdc_generated(from: "Beach.longitude", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Beach.id", purpose: GLOBAL_ID)
}
extend type Comment {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Comment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Comment` table.
  """
  _count: Int! @fdc_generated(from: "Comment.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Comment` table where the `beachId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  beachId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Comment.beachId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Comment` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Comment.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Comment` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Comment.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Comment` table where the `text` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  text_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Comment.text", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Comment` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Comment.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Comment` table.
  """
  createdAt_min: Date @fdc_generated(from: "Comment.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Comment` table.
  """
  createdAt_max: Date @fdc_generated(from: "Comment.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Comment.id", purpose: GLOBAL_ID)
}
extend type Report {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Report", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Report` table.
  """
  _count: Int! @fdc_generated(from: "Report.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `accessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  accessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.accessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `blockerName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  blockerName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.blockerName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `blockerType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  blockerType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.blockerType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `feeAmount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  feeAmount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.feeAmount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `hasIllegalFee` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hasIllegalFee_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.hasIllegalFee", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `reporterName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reporterName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.reporterName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `score` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  score_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.score", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Report` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Report.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `feeAmount` field in the `Report` table.
  """
  feeAmount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Report.feeAmount", purpose: QUERY_SUM)
  """
  ✨ Sum the `score` field in the `Report` table.
  """
  score_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Report.score", purpose: QUERY_SUM)
  """
  ✨ Average the `feeAmount` field in the `Report` table.
  """
  feeAmount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Report.feeAmount", purpose: QUERY_AVG)
  """
  ✨ Average the `score` field in the `Report` table.
  """
  score_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Report.score", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Report` table.
  """
  createdAt_min: Date @fdc_generated(from: "Report.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `feeAmount` field in the `Report` table.
  """
  feeAmount_min: Float @fdc_generated(from: "Report.feeAmount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `score` field in the `Report` table.
  """
  score_min: Int @fdc_generated(from: "Report.score", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Report` table.
  """
  createdAt_max: Date @fdc_generated(from: "Report.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `feeAmount` field in the `Report` table.
  """
  feeAmount_max: Float @fdc_generated(from: "Report.feeAmount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `score` field in the `Report` table.
  """
  score_max: Int @fdc_generated(from: "Report.score", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Report.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Access` objects in a one-to-many relationship (where `Access`.`user` is this object).
  """
  accesses_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Access_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Access_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Access_Having
  ): [Access!]! @fdc_generated(from: "Access.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Beach` objects in a one-to-many relationship (where `Beach`.`user` is this object).
  """
  beaches_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Beach_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Beach_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Beach_Having
  ): [Beach!]! @fdc_generated(from: "Beach.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Comment` objects in a one-to-many relationship (where `Comment`.`user` is this object).
  """
  comments_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Comment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Comment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Comment_Having
  ): [Comment!]! @fdc_generated(from: "Comment.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Report` objects in a one-to-many relationship (where `Report`.`user` is this object).
  """
  reports_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Report_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Report_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Report_Having
  ): [Report!]! @fdc_generated(from: "Report.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `avatarUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  avatarUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.avatarUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `bio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.bio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `reputation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reputation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.reputation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Sum the `reputation` field in the `User` table.
  """
  reputation_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.reputation", purpose: QUERY_SUM)
  """
  ✨ Average the `reputation` field in the `User` table.
  """
  reputation_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.reputation", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Date @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `reputation` field in the `User` table.
  """
  reputation_min: Int @fdc_generated(from: "User.reputation", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Date @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `reputation` field in the `User` table.
  """
  reputation_max: Int @fdc_generated(from: "User.reputation", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
